<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Akka" />
      <PackageReference Include="Akka.Hosting" />
      <PackageReference Include="Flurl.Http" />
      <PackageReference Include="LanguageExt.Core" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
      <PackageReference Include="Microsoft.Maui.Controls.Core" />
      <PackageReference Include="ReactiveMarbles.Mvvm" />
      <PackageReference Include="Riok.Mapperly" />
    </ItemGroup>

    <ItemGroup>
      <InternalsVisibleTo Include="Transponder.UnitTests" />
    </ItemGroup>

</Project>
