<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup Label="Analysis">
    <PackageVersion Include="Akka" Version="1.5.8" />
    <PackageVersion Include="Akka.Hosting" Version="1.5.8" />
    <PackageVersion Include="Akka.Hosting.Maui" Version="1.5.8" />
    <PackageVersion Include="CommunityToolkit.Maui.Markup" Version="8.0.0" />
    <PackageVersion Include="Flurl" Version="4.0.0" />
    <PackageVersion Include="Flurl.Http" Version="4.0.2" />
    <PackageVersion Include="DynamicData" Version="9.4.33" />
    <PackageVersion Include="LanguageExt.Core" Version="4.4.9" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Maui.Controls.Core" Version="10.0.110" />
    <PackageVersion Include="ReactiveMarbles.Mvvm" Version="1.0.95" />
    <PackageVersion Include="Riok.Mapperly" Version="4.3.1" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="5.0.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="5.0.0" />
    <PackageVersion Include="Rocket.Surgery.Airframe.CodeAnalysis" Version="0.12.2" />
  </ItemGroup>
  <ItemGroup Label="Build">
    <PackageVersion Include="Nuke.Common" Version="10.1.0" />
  </ItemGroup>
  <ItemGroup Label="Maui">
    <PackageVersion Include="Microsoft.Maui.Controls" Version="10.0.110" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Debug" Version="10.0.0" />
  </ItemGroup>
  <ItemGroup Label="Test">
    <PackageVersion Include="AwesomeAssertions" Version="9.6.0" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageVersion Include="NSubstitute" Version="6.2.0" />
    <PackageVersion Include="Rocket.Surgery.Extensions.Testing.AutoFixtures" Version="10.0.6" />
    <PackageVersion Include="Rocket.Surgery.Extensions.Testing.SourceGenerators" Version="10.0.1" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>
</Project>