<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup Label="Analysis">
    <PackageVersion Include="Rocket.Surgery.Airframe.CodeAnalysis" Version="0.12.2" />
  </ItemGroup>
  <ItemGroup Label="Build">
    <PackageVersion Include="Nuke.Common" Version="10.1.0" />
  </ItemGroup>
  <ItemGroup Label="Maui">
    <PackageVersion Include="Microsoft.Maui.Controls" Version="10.0.110" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Debug" Version="10.0.0" />
  </ItemGroup>
  <ItemGroup Label="Test">
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>
</Project>