<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <RootNamespace>Transponder.UnitTests</RootNamespace>
        <AssemblyName>Transponder.UnitTests</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AwesomeAssertions"/>
        <PackageReference Include="coverlet.collector"/>
        <PackageReference Include="Microsoft.Extensions.Hosting"/>
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="Microsoft.Reactive.Testing"/>
        <PackageReference Include="NSubstitute"/>
        <PackageReference Include="Rocket.Surgery.Extensions.Testing.AutoFixtures"/>
        <PackageReference Include="Rocket.Surgery.Extensions.Testing.SourceGenerators"/>
        <PackageReference Include="xunit"/>
        <PackageReference Include="xunit.runner.visualstudio"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../src/Transponder/Transponder.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

</Project>